server:
  port: 8080

spring:
  application:
    name: jenksy-mcp

  cache:
    type: caffeine

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.jenksy.jenksymcp: INFO