server:
  port: 8080

spring:
  application:
    name: jenksy-mcp

  cache:
    type: caffeine

jenksy:
  mcp:
    stats:
      persistence:
        enabled: true
        interval-minutes: 5
        file-path: agent-stats.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.jenksy.jenksymcp: INFO